import { useState, useEffect } from 'react'
import { Helmet } from 'react-helmet-async'
import SEO from '../components/SEO'
import GlobalHeader from '../components/GlobalHeader'
import FooterV9 from '../components/FooterV9'
import { pageUrl, alternatesFor } from '../lib/localeUrls'

// Pagina /campanii — campanii Google Shopping prin CSS, comparator de prețuri,
// vizibilitate AI și grila oficială de prețuri (10.10.2026).
// RO = conținut verbatim aprobat de Adrian; EN/ES/PT/FR = traduceri ale aceluiași
// conținut (structura multi-limbă identică cu GoogleShoppingFeed).
// Layout: GlobalHeader + FooterV9 (aceleași cu restul paginilor standalone).

const SLUG = 'campanii'

const T = {
  en: {
    meta: {
      title: 'Google Shopping Campaigns & Price Comparison — CatyAI',
      desc: 'CatyAI: Google Shopping campaigns through CSS with up to ~20% savings per click, price comparison with EAN/GTIN semantic engine and visibility in AI search.',
    },
    hero: {
      eyebrow: 'CSS · Price comparison · AI visibility',
      titlePre: 'Your products, ',
      titleAccent: 'first in Google Shopping',
      titlePost: '. At the right cost.',
      sub: 'We are a Google-authorised CSS operator and we build the price comparison engine with our own semantic core. We connect your catalog, clean up your feed and bring your products exactly where buyers are searching.',
      cta1: 'Get free consultation',
      cta2: 'See pricing',
    },
    stats: [
      { v: '2.8M+', l: 'products in our comparison engine' },
      { v: '3.7M', l: 'vectors in the semantic engine' },
      { v: '500,000+', l: 'products processed daily from feeds' },
      { v: '24–48h', l: 'CSS activation for your store' },
    ],
    css: {
      eyebrow: 'Google Shopping via CSS',
      h2: 'Same click, up to ~20% cheaper',
      p: 'As a CSS (Comparison Shopping Services) partner, we list your products in Google Shopping through our infrastructure — not through the standard Google account. The CSS programme mechanism reduces the real cost of the click, and the difference stays with you.',
      bullets: [
        'Your products appear in Shopping without the standard auction markup',
        'You keep full control: you choose which products and what budget to promote',
        'Migration from your Merchant Center account with no loss of performance history',
        'Transparent reporting — you see exactly what you pay and what you get',
      ],
      badge: 'Up to ~20% savings per click, through the official CSS mechanism',
    },
    comparator: {
      eyebrow: 'Price comparison with a semantic engine',
      h2: 'Same product, all prices. No duplicates.',
      p: 'Our comparison engine does not match products by title. Our own semantic engine understands what the product is and links it based on EAN/GTIN codes — so the same product from 5 stores appears once, with all 5 prices side by side.',
      bullets: [
        'Over 2.8 million products indexed and updated daily',
        'EAN/GTIN matching + semantic matching for products without a code',
        'Similar offers generated by the vector engine, not manual rules',
        'Traffic from the comparison engine goes straight to your product page',
      ],
    },
    ai: {
      eyebrow: 'Visibility in AI search',
      h2: 'When the customer asks the AI, the answer should be your product',
      p: 'More and more buyers no longer search on Google — they ask ChatGPT, Gemini or Perplexity. We optimize your catalog structure (structured data, clean feeds, machine-readable content) so AI assistants find you and recommend you.',
      bullets: [
        'Structured data and feeds prepared for consumption by AI agents',
        'Indexable, fast product pages with correct price and availability',
        'We monitor how you appear in AI answers and continuously adjust',
      ],
    },
    services: {
      eyebrow: 'What we actually do',
      h2: 'The complete infrastructure of your catalog',
      sub: 'We don\'t sell promises. We operate feeds, Merchant Center accounts and data pipelines daily — exactly what you see below.',
      items: [
        { h: 'Feed management', p: 'We clean, complete and validate your product feed: titles, attributes, GTINs, Google categories. The feed is the foundation — everything else depends on it.' },
        { h: 'Google Merchant Center', p: 'We set up and manage Merchant Center accounts, including multi-account architectures. We resolve suspensions, warnings and feed errors.' },
        { h: 'Price comparison', p: 'We list your products in our comparison engine, with prices updated daily and traffic sent straight to your product pages.' },
        { h: 'CSS campaigns', p: 'We move your Shopping campaigns to our CSS, with up to ~20% savings per click and the same visibility in Google.' },
        { h: 'AI visibility (GEO)', p: 'We prepare your catalog for the era of conversational search: AI assistants read, understand and recommend your products.' },
        { h: 'Marketplace Sync', p: 'Add-on for syncing your catalog with marketplaces: stock and prices aligned automatically across all channels.' },
      ],
    },
    steps: {
      eyebrow: 'How it works',
      h2: 'From feed to sale, in three steps',
      items: [
        { h: 'Free feed audit', p: 'We analyze your catalog and tell you concretely what is missing: GTINs, attributes, Merchant Center errors, matching opportunities in the comparison engine.' },
        { h: 'Connection and activation', p: 'We connect your store to our CSS and to the comparison engine. Activation takes 24–48 hours, with no changes to your website.' },
        { h: 'Daily monitoring', p: 'We track prices, availability and performance. You get clear reports: what sold, what the click costs, where you can grow.' },
      ],
    },
    pricing: {
      eyebrow: 'Transparent pricing',
      h2: 'Official CatyAI pricing',
      sub: 'One-time setup + monthly subscription + commission on ad budget. No hidden costs, no trial periods — with measurable results.',
      badge: 'LAUNCH PRICING',
      setupSuffix: ' setup',
      monthlySuffix: '/month',
      commission: 'Commission',
      adBudget: ' of ad budget',
      plans: [
        { name: 'Entry', launch: true, sku: 'up to 1,000 SKUs', setup: '€500', monthly: '€200', commission: '5%', features: ['Comparison engine listing', 'Monthly report'] },
        { name: 'Starter', launch: true, sku: '1,001–3,000 SKUs', setup: '€700', monthly: '€250', commission: '5%', features: ['CSS + comparison engine', 'Feed management'] },
        { name: 'Growth', sku: '3,001–10,000 SKUs', setup: '€3,000', monthly: '€600', commission: '5%', features: ['Everything in Starter', 'GTIN semantic optimization'] },
        { name: 'Pro', sku: '10,001–50,000 SKUs', setup: '€6,000', monthly: '€1,200', commission: '4%', features: ['AI visibility included', 'Dedicated manager'] },
        { name: 'Enterprise', sku: 'over 50,000 SKUs', setup: 'custom', monthly: '', commission: '3–4%', features: ['Multi-account GMC architecture', 'SLA and API integration'] },
      ],
      addons: [
        { h: 'Marketplace Sync', p: '€200 setup/channel + €150/month (standalone: €300 setup + €200/month). Stock and price sync with marketplaces.' },
        { h: 'Additional channels', p: '+€50/month for each extra channel on Entry and Starter plans.' },
      ],
      note: 'Launch pricing is valid for the first 10 clients, until 31.12.2026. Terms: setup paid at signing, minimum 6-month period for Entry and Starter. Prices shown do not include VAT.',
    },
    faq: {
      h2: 'Frequently asked questions',
      items: [
        { q: 'What is CSS and why is the click cheaper?', a: 'CSS (Comparison Shopping Services) is the Google programme through which independent price comparison services — like us — can list products in Google Shopping. Auctions through a CSS have a cost advantage built into the Google mechanism, which translates into up to ~20% savings per click compared to the standard account. Product visibility stays identical.' },
        { q: 'Do I need to change anything in my online store?', a: 'No. We work on the product feed you already have (or we build it for you). We don\'t install scripts in your site and we don\'t touch your platform — whether it\'s GoMag, Shopify, WooCommerce or anything else.' },
        { q: 'How long until my products appear?', a: 'CSS activation and listing in the comparison engine takes 24–48 hours from receiving a valid feed. The first feed optimization (if needed) usually adds another 1–2 days.' },
        { q: 'What does "AI visibility" mean concretely?', a: 'AI assistants (ChatGPT, Gemini, Perplexity) recommend products based on data they can read and understand. We make sure your catalog has correctly structured data, real prices and indexable pages — the conditions for an AI to be able to cite you. We monitor your presence in AI answers and report on it.' },
        { q: 'Can I cancel anytime?', a: 'The minimum period is 6 months for the Entry and Starter plans (the real time in which a channel like this reaches performance). After that, the collaboration continues monthly, with no obligations.' },
      ],
    },
    finalCta: {
      h2: 'Get your free feed audit',
      p: 'Within 48 hours we tell you what you are losing right now: overpriced clicks, invisible products, missing GTINs.',
      cta: 'contact@catyai.io',
    },
  },

  ro: {
    meta: {
      title: 'Campanii Google Shopping & Comparator de Prețuri — CatyAI',
      desc: 'CatyAI: campanii Google Shopping prin CSS cu până la ~20% economie pe clic, comparator de prețuri cu motor semantic EAN/GTIN și vizibilitate în căutările AI.',
    },
    hero: {
      eyebrow: 'CSS · Comparator de prețuri · Vizibilitate AI',
      titlePre: 'Produsele tale, ',
      titleAccent: 'pe primul loc',
      titlePost: ' în Google Shopping. La cost corect.',
      sub: 'Suntem operator CSS autorizat Google și construim comparatorul de prețuri cu motor semantic propriu. Îți conectăm catalogul, îți curățăm feedul și îți aducem produsele exact acolo unde caută cumpărătorii.',
      cta1: 'Cere consultanță gratuită',
      cta2: 'Vezi prețurile',
    },
    stats: [
      { v: '2,8 mil.+', l: 'produse în comparatorul nostru' },
      { v: '3,7 mil.', l: 'vectori în motorul semantic' },
      { v: '500.000+', l: 'produse procesate zilnic din feeduri' },
      { v: '24–48h', l: 'activare CSS pentru magazinul tău' },
    ],
    css: {
      eyebrow: 'Google Shopping prin CSS',
      h2: 'Același clic, cu până la ~20% mai ieftin',
      p: 'Ca partener CSS (Comparison Shopping Services), listăm produsele tale în Google Shopping prin infrastructura noastră — nu prin contul standard Google. Mecanismul programului CSS reduce costul real al clicului, iar diferența rămâne la tine.',
      bullets: [
        'Produsele tale apar în Shopping fără supraprețul licitației standard',
        'Păstrezi controlul total: alegi ce produse și ce buget promovezi',
        'Migrare din contul tău Merchant Center fără pierdere de istoric de performanță',
        'Raportare transparentă — vezi exact ce plătești și ce primești',
      ],
      badge: 'Până la ~20% economie pe clic, prin mecanismul oficial CSS',
    },
    comparator: {
      eyebrow: 'Comparator de prețuri cu motor semantic',
      h2: 'Același produs, toate prețurile. Fără duplicate.',
      p: 'Comparatorul nostru nu potrivește produse după titlu. Motorul semantic propriu înțelege ce este produsul și îl leagă pe baza codurilor EAN/GTIN — astfel același produs de la 5 magazine apare o singură dată, cu toate cele 5 prețuri alăturate.',
      bullets: [
        'Peste 2,8 milioane de produse indexate și actualizate zilnic',
        'Potrivire EAN/GTIN + matching semantic pentru produsele fără cod',
        'Oferte similare generate de motorul de vectori, nu de reguli manuale',
        'Traficul de pe comparator ajunge direct pe pagina ta de produs',
      ],
    },
    ai: {
      eyebrow: 'Vizibilitate în căutările AI',
      h2: 'Când clientul întreabă AI-ul, răspunsul să fie produsul tău',
      p: 'Tot mai mulți cumpărători nu mai caută pe Google — întreabă ChatGPT, Gemini sau Perplexity. Optimizăm structura catalogului tău (date structurate, feeduri curate, conținut citibil de mașini) astfel încât asistenții AI să te găsească și să te recomande.',
      bullets: [
        'Date structurate și feeduri pregătite pentru consumul de către agenții AI',
        'Pagini de produs indexabile, rapide, cu preț și disponibilitate corecte',
        'Monitorizăm cum apari în răspunsurile AI și ajustăm continuu',
      ],
    },
    services: {
      eyebrow: 'Ce facem concret',
      h2: 'Infrastructura completă a catalogului tău',
      sub: 'Nu vindem promisiuni. Operăm zilnic feeduri, conturi Merchant Center și pipeline-uri de date — exact ce vezi mai jos.',
      items: [
        { h: 'Feed management', p: 'Curățăm, completăm și validăm feedul de produse: titluri, atribute, GTIN-uri, categorii Google. Feedul este fundația — de el depinde tot restul.' },
        { h: 'Google Merchant Center', p: 'Configurăm și administrăm conturile Merchant Center, inclusiv arhitecturi multi-cont. Rezolvăm suspendări, avertismente și erori de feed.' },
        { h: 'Comparator de prețuri', p: 'Îți listăm produsele în comparatorul nostru, cu prețuri actualizate zilnic și trafic trimis direct către paginile tale de produs.' },
        { h: 'Campanii CSS', p: 'Mutăm campaniile Shopping pe CSS-ul nostru, cu economie de până la ~20% pe clic și aceeași vizibilitate în Google.' },
        { h: 'Vizibilitate AI (GEO)', p: 'Pregătim catalogul pentru era căutării conversaționale: asistenții AI citesc, înțeleg și recomandă produsele tale.' },
        { h: 'Marketplace Sync', p: 'Add-on de sincronizare a catalogului cu marketplace-uri: stocuri și prețuri aliniate automat pe toate canalele.' },
      ],
    },
    steps: {
      eyebrow: 'Cum funcționează',
      h2: 'De la feed la vânzare, în trei pași',
      items: [
        { h: 'Audit gratuit al feedului', p: 'Analizăm catalogul tău și îți spunem concret ce lipsește: GTIN-uri, atribute, erori de Merchant Center, oportunități de potrivire în comparator.' },
        { h: 'Conectare și activare', p: 'Îți conectăm magazinul la CSS-ul nostru și la comparator. Activarea durează 24–48 de ore, fără modificări în site-ul tău.' },
        { h: 'Monitorizare zilnică', p: 'Urmărim prețurile, disponibilitatea și performanța. Primești rapoarte clare: ce s-a vândut, ce costă clicul, unde poți crește.' },
      ],
    },
    pricing: {
      eyebrow: 'Prețuri transparente',
      h2: 'Grila oficială CatyAI',
      sub: 'Setup unic + abonament lunar + comision din bugetul de ads. Fără costuri ascunse, fără perioade de probă — cu rezultate măsurabile.',
      badge: 'TARIF LANSARE',
      setupSuffix: ' setup',
      monthlySuffix: '/lună',
      commission: 'Comision',
      adBudget: ' din bugetul ads',
      plans: [
        { name: 'Entry', launch: true, sku: 'până la 1.000 SKU', setup: '500€', monthly: '200€', commission: '5%', features: ['Listare în comparator', 'Raport lunar'] },
        { name: 'Starter', launch: true, sku: '1.001–3.000 SKU', setup: '700€', monthly: '250€', commission: '5%', features: ['CSS + comparator', 'Feed management'] },
        { name: 'Growth', sku: '3.001–10.000 SKU', setup: '3.000€', monthly: '600€', commission: '5%', features: ['Tot din Starter', 'Optimizare semantică GTIN'] },
        { name: 'Pro', sku: '10.001–50.000 SKU', setup: '6.000€', monthly: '1.200€', commission: '4%', features: ['Vizibilitate AI inclusă', 'Manager dedicat'] },
        { name: 'Enterprise', sku: 'peste 50.000 SKU', setup: 'custom', monthly: '', commission: '3–4%', features: ['Arhitectură multi-cont GMC', 'SLA și integrare API'] },
      ],
      addons: [
        { h: 'Marketplace Sync', p: '200€ setup/canal + 150€/lună (standalone: 300€ setup + 200€/lună). Sincronizare stocuri și prețuri cu marketplace-urile.' },
        { h: 'Canale suplimentare', p: '+50€/lună pentru fiecare canal extra la pachetele Entry și Starter.' },
      ],
      note: 'Tariful de lansare este valabil pentru primii 10 clienți, până la 31.12.2026. Condiții: setup plătit la semnare, perioadă minimă 6 luni pentru Entry și Starter. Tarifele afișate nu includ TVA.',
    },
    faq: {
      h2: 'Întrebări frecvente',
      items: [
        { q: 'Ce este CSS și de ce e clicul mai ieftin?', a: 'CSS (Comparison Shopping Services) este programul Google prin care servicii independente de comparare a prețurilor — cum suntem noi — pot lista produse în Google Shopping. Licitația printr-un CSS are un avantaj de cost integrat în mecanismul Google, ceea ce se traduce în până la ~20% economie pe clic față de contul standard. Vizibilitatea produselor rămâne identică.' },
        { q: 'Trebuie să modific ceva în magazinul meu online?', a: 'Nu. Lucrăm pe baza feedului de produse pe care îl ai deja (sau îl construim noi). Nu instalăm scripturi în site și nu atingem platforma ta — indiferent dacă e GoMag, Shopify, WooCommerce sau altceva.' },
        { q: 'Cât durează până apar produsele mele?', a: 'Activarea CSS și listarea în comparator durează 24–48 de ore de la primirea feedului valid. Prima optimizare de feed (dacă e necesară) adaugă, de regulă, încă 1–2 zile.' },
        { q: 'Ce înseamnă «vizibilitate AI» concret?', a: 'Asistenții AI (ChatGPT, Gemini, Perplexity) recomandă produse pe baza datelor pe care le pot citi și înțelege. Noi ne asigurăm că catalogul tău are date structurate corecte, prețuri reale și pagini indexabile — condițiile ca un AI să te poată cita. Monitorizăm prezența ta în răspunsurile AI și raportăm.' },
        { q: 'Pot renunța oricând?', a: 'Perioada minimă este de 6 luni pentru pachetele Entry și Starter (timpul real în care un canal de acest tip ajunge la performanță). După aceea, colaborarea continuă lunar, fără obligații.' },
      ],
    },
    finalCta: {
      h2: 'Cere auditul gratuit al feedului tău',
      p: 'Îți spunem în 48 de ore ce pierzi acum: clicuri plătite prea scump, produse invizibile, GTIN-uri lipsă.',
      cta: 'contact@catyai.io',
    },
  },

  es: {
    meta: {
      title: 'Campañas de Google Shopping y Comparador de Precios — CatyAI',
      desc: 'CatyAI: campañas de Google Shopping a través de CSS con hasta ~20% de ahorro por clic, comparador de precios con motor semántico EAN/GTIN y visibilidad en búsquedas de IA.',
    },
    hero: {
      eyebrow: 'CSS · Comparador de precios · Visibilidad en IA',
      titlePre: 'Tus productos, ',
      titleAccent: 'en primer lugar',
      titlePost: ' en Google Shopping. Al coste correcto.',
      sub: 'Somos operador CSS autorizado por Google y construimos el comparador de precios con motor semántico propio. Conectamos tu catálogo, limpiamos tu feed y llevamos tus productos exactamente donde buscan los compradores.',
      cta1: 'Pide consultoría gratuita',
      cta2: 'Ver precios',
    },
    stats: [
      { v: '2,8 M+', l: 'productos en nuestro comparador' },
      { v: '3,7 M', l: 'vectores en el motor semántico' },
      { v: '500.000+', l: 'productos procesados a diario desde feeds' },
      { v: '24–48h', l: 'activación CSS para tu tienda' },
    ],
    css: {
      eyebrow: 'Google Shopping a través de CSS',
      h2: 'El mismo clic, hasta ~20% más barato',
      p: 'Como partner CSS (Comparison Shopping Services), listamos tus productos en Google Shopping a través de nuestra infraestructura — no a través de la cuenta estándar de Google. El mecanismo del programa CSS reduce el coste real del clic, y la diferencia se queda contigo.',
      bullets: [
        'Tus productos aparecen en Shopping sin el sobreprecio de la subasta estándar',
        'Mantienes el control total: eliges qué productos y qué presupuesto promocionar',
        'Migración desde tu cuenta de Merchant Center sin pérdida de historial de rendimiento',
        'Informes transparentes — ves exactamente qué pagas y qué recibes',
      ],
      badge: 'Hasta ~20% de ahorro por clic, a través del mecanismo oficial CSS',
    },
    comparator: {
      eyebrow: 'Comparador de precios con motor semántico',
      h2: 'El mismo producto, todos los precios. Sin duplicados.',
      p: 'Nuestro comparador no empareja productos por título. El motor semántico propio entiende qué es el producto y lo vincula mediante códigos EAN/GTIN — así el mismo producto de 5 tiendas aparece una sola vez, con los 5 precios juntos.',
      bullets: [
        'Más de 2,8 millones de productos indexados y actualizados a diario',
        'Emparejamiento EAN/GTIN + emparejamiento semántico para productos sin código',
        'Ofertas similares generadas por el motor de vectores, no por reglas manuales',
        'El tráfico del comparador llega directamente a tu página de producto',
      ],
    },
    ai: {
      eyebrow: 'Visibilidad en búsquedas de IA',
      h2: 'Cuando el cliente pregunta a la IA, la respuesta debe ser tu producto',
      p: 'Cada vez más compradores ya no buscan en Google — preguntan a ChatGPT, Gemini o Perplexity. Optimizamos la estructura de tu catálogo (datos estructurados, feeds limpios, contenido legible por máquinas) para que los asistentes de IA te encuentren y te recomienden.',
      bullets: [
        'Datos estructurados y feeds preparados para el consumo de agentes de IA',
        'Páginas de producto indexables, rápidas, con precio y disponibilidad correctos',
        'Monitorizamos cómo apareces en las respuestas de la IA y ajustamos continuamente',
      ],
    },
    services: {
      eyebrow: 'Qué hacemos concretamente',
      h2: 'La infraestructura completa de tu catálogo',
      sub: 'No vendemos promesas. Operamos feeds, cuentas de Merchant Center y pipelines de datos a diario — exactamente lo que ves abajo.',
      items: [
        { h: 'Feed management', p: 'Limpiamos, completamos y validamos tu feed de productos: títulos, atributos, GTIN, categorías de Google. El feed es la base — de él depende todo lo demás.' },
        { h: 'Google Merchant Center', p: 'Configuramos y gestionamos cuentas de Merchant Center, incluidas arquitecturas multi-cuenta. Resolvemos suspensiones, avisos y errores de feed.' },
        { h: 'Comparador de precios', p: 'Listamos tus productos en nuestro comparador, con precios actualizados a diario y tráfico enviado directamente a tus páginas de producto.' },
        { h: 'Campañas CSS', p: 'Movemos tus campañas de Shopping a nuestro CSS, con ahorro de hasta ~20% por clic y la misma visibilidad en Google.' },
        { h: 'Visibilidad en IA (GEO)', p: 'Preparamos tu catálogo para la era de la búsqueda conversacional: los asistentes de IA leen, entienden y recomiendan tus productos.' },
        { h: 'Marketplace Sync', p: 'Add-on de sincronización del catálogo con marketplaces: stocks y precios alineados automáticamente en todos los canales.' },
      ],
    },
    steps: {
      eyebrow: 'Cómo funciona',
      h2: 'Del feed a la venta, en tres pasos',
      items: [
        { h: 'Auditoría gratuita del feed', p: 'Analizamos tu catálogo y te decimos concretamente qué falta: GTIN, atributos, errores de Merchant Center, oportunidades de emparejamiento en el comparador.' },
        { h: 'Conexión y activación', p: 'Conectamos tu tienda a nuestro CSS y al comparador. La activación dura 24–48 horas, sin modificaciones en tu sitio.' },
        { h: 'Monitorización diaria', p: 'Seguimos precios, disponibilidad y rendimiento. Recibes informes claros: qué se vendió, qué cuesta el clic, dónde puedes crecer.' },
      ],
    },
    pricing: {
      eyebrow: 'Precios transparentes',
      h2: 'Tarifa oficial CatyAI',
      sub: 'Setup único + suscripción mensual + comisión sobre el presupuesto de ads. Sin costes ocultos, sin períodos de prueba — con resultados medibles.',
      badge: 'TARIFA DE LANZAMIENTO',
      setupSuffix: ' setup',
      monthlySuffix: '/mes',
      commission: 'Comisión',
      adBudget: ' del presupuesto de ads',
      plans: [
        { name: 'Entry', launch: true, sku: 'hasta 1.000 SKU', setup: '500€', monthly: '200€', commission: '5%', features: ['Listado en el comparador', 'Informe mensual'] },
        { name: 'Starter', launch: true, sku: '1.001–3.000 SKU', setup: '700€', monthly: '250€', commission: '5%', features: ['CSS + comparador', 'Feed management'] },
        { name: 'Growth', sku: '3.001–10.000 SKU', setup: '3.000€', monthly: '600€', commission: '5%', features: ['Todo lo de Starter', 'Optimización semántica GTIN'] },
        { name: 'Pro', sku: '10.001–50.000 SKU', setup: '6.000€', monthly: '1.200€', commission: '4%', features: ['Visibilidad en IA incluida', 'Manager dedicado'] },
        { name: 'Enterprise', sku: 'más de 50.000 SKU', setup: 'custom', monthly: '', commission: '3–4%', features: ['Arquitectura multi-cuenta GMC', 'SLA e integración API'] },
      ],
      addons: [
        { h: 'Marketplace Sync', p: '200€ setup/canal + 150€/mes (standalone: 300€ setup + 200€/mes). Sincronización de stocks y precios con marketplaces.' },
        { h: 'Canales adicionales', p: '+50€/mes por cada canal extra en los planes Entry y Starter.' },
      ],
      note: 'La tarifa de lanzamiento es válida para los primeros 10 clientes, hasta el 31.12.2026. Condiciones: setup pagado al firmar, período mínimo de 6 meses para Entry y Starter. Los precios mostrados no incluyen IVA.',
    },
    faq: {
      h2: 'Preguntas frecuentes',
      items: [
        { q: '¿Qué es CSS y por qué el clic es más barato?', a: 'CSS (Comparison Shopping Services) es el programa de Google a través del cual servicios independientes de comparación de precios — como nosotros — pueden listar productos en Google Shopping. La subasta a través de un CSS tiene una ventaja de coste integrada en el mecanismo de Google, lo que se traduce en hasta ~20% de ahorro por clic respecto a la cuenta estándar. La visibilidad de los productos se mantiene idéntica.' },
        { q: '¿Tengo que modificar algo en mi tienda online?', a: 'No. Trabajamos sobre el feed de productos que ya tienes (o lo construimos nosotros). No instalamos scripts en tu sitio y no tocamos tu plataforma — sea GoMag, Shopify, WooCommerce o cualquier otra.' },
        { q: '¿Cuánto tardan en aparecer mis productos?', a: 'La activación CSS y el listado en el comparador tarda 24–48 horas desde la recepción del feed válido. La primera optimización del feed (si es necesaria) suele añadir otros 1–2 días.' },
        { q: '¿Qué significa «visibilidad en IA» concretamente?', a: 'Los asistentes de IA (ChatGPT, Gemini, Perplexity) recomiendan productos basándose en los datos que pueden leer y entender. Nos aseguramos de que tu catálogo tenga datos estructurados correctos, precios reales y páginas indexables — las condiciones para que una IA pueda citarte. Monitorizamos tu presencia en las respuestas de la IA e informamos.' },
        { q: '¿Puedo darme de baja cuando quiera?', a: 'El período mínimo es de 6 meses para los planes Entry y Starter (el tiempo real en el que un canal de este tipo alcanza rendimiento). Después, la colaboración continúa mes a mes, sin obligaciones.' },
      ],
    },
    finalCta: {
      h2: 'Pide la auditoría gratuita de tu feed',
      p: 'Te decimos en 48 horas qué estás perdiendo ahora: clics pagados demasiado caros, productos invisibles, GTIN que faltan.',
      cta: 'contact@catyai.io',
    },
  },

  pt: {
    meta: {
      title: 'Campanhas Google Shopping & Comparador de Preços — CatyAI',
      desc: 'CatyAI: campanhas Google Shopping através de CSS com até ~20% de poupança por clique, comparador de preços com motor semântico EAN/GTIN e visibilidade nas pesquisas de IA.',
    },
    hero: {
      eyebrow: 'CSS · Comparador de preços · Visibilidade em IA',
      titlePre: 'Os teus produtos, ',
      titleAccent: 'em primeiro lugar',
      titlePost: ' no Google Shopping. Ao custo certo.',
      sub: 'Somos operador CSS autorizado pelo Google e construímos o comparador de preços com motor semântico próprio. Ligamos o teu catálogo, limpamos o teu feed e trazemos os teus produtos exatamente onde os compradores procuram.',
      cta1: 'Pedir consultoria gratuita',
      cta2: 'Ver preços',
    },
    stats: [
      { v: '2,8 M+', l: 'produtos no nosso comparador' },
      { v: '3,7 M', l: 'vetores no motor semântico' },
      { v: '500.000+', l: 'produtos processados diariamente a partir de feeds' },
      { v: '24–48h', l: 'ativação CSS para a tua loja' },
    ],
    css: {
      eyebrow: 'Google Shopping através de CSS',
      h2: 'O mesmo clique, até ~20% mais barato',
      p: 'Como parceiro CSS (Comparison Shopping Services), listamos os teus produtos no Google Shopping através da nossa infraestrutura — não através da conta padrão do Google. O mecanismo do programa CSS reduz o custo real do clique, e a diferença fica contigo.',
      bullets: [
        'Os teus produtos aparecem no Shopping sem o sobrepreco do leilão padrão',
        'Manténs o controlo total: escolhes que produtos e que orçamento promover',
        'Migração da tua conta Merchant Center sem perda de histórico de desempenho',
        'Relatórios transparentes — vês exatamente o que pagas e o que recebes',
      ],
      badge: 'Até ~20% de poupança por clique, através do mecanismo oficial CSS',
    },
    comparator: {
      eyebrow: 'Comparador de preços com motor semântico',
      h2: 'O mesmo produto, todos os preços. Sem duplicados.',
      p: 'O nosso comparador não faz correspondência de produtos por título. O motor semântico próprio percebe o que é o produto e liga-o com base nos códigos EAN/GTIN — assim o mesmo produto de 5 lojas aparece uma única vez, com os 5 preços lado a lado.',
      bullets: [
        'Mais de 2,8 milhões de produtos indexados e atualizados diariamente',
        'Correspondência EAN/GTIN + correspondência semântica para produtos sem código',
        'Ofertas semelhantes geradas pelo motor de vetores, não por regras manuais',
        'O tráfego do comparador chega diretamente à tua página de produto',
      ],
    },
    ai: {
      eyebrow: 'Visibilidade nas pesquisas de IA',
      h2: 'Quando o cliente pergunta à IA, a resposta deve ser o teu produto',
      p: 'Cada vez mais compradores já não pesquisam no Google — perguntam ao ChatGPT, Gemini ou Perplexity. Otimizamos a estrutura do teu catálogo (dados estruturados, feeds limpos, conteúdo legível por máquinas) para que os assistentes de IA te encontrem e recomendem.',
      bullets: [
        'Dados estruturados e feeds preparados para consumo por agentes de IA',
        'Páginas de produto indexáveis, rápidas, com preço e disponibilidade corretos',
        'Monitorizamos como apareces nas respostas da IA e ajustamos continuamente',
      ],
    },
    services: {
      eyebrow: 'O que fazemos concretamente',
      h2: 'A infraestrutura completa do teu catálogo',
      sub: 'Não vendemos promessas. Operamos feeds, contas Merchant Center e pipelines de dados diariamente — exatamente o que vês abaixo.',
      items: [
        { h: 'Feed management', p: 'Limpamos, completamos e validamos o teu feed de produtos: títulos, atributos, GTIN, categorias do Google. O feed é a base — dele depende todo o resto.' },
        { h: 'Google Merchant Center', p: 'Configuramos e gerimos contas Merchant Center, incluindo arquiteturas multi-conta. Resolvemos suspensões, avisos e erros de feed.' },
        { h: 'Comparador de preços', p: 'Listamos os teus produtos no nosso comparador, com preços atualizados diariamente e tráfego enviado diretamente para as tuas páginas de produto.' },
        { h: 'Campanhas CSS', p: 'Movemos as tuas campanhas de Shopping para o nosso CSS, com poupança de até ~20% por clique e a mesma visibilidade no Google.' },
        { h: 'Visibilidade em IA (GEO)', p: 'Preparamos o teu catálogo para a era da pesquisa conversacional: os assistentes de IA leem, percebem e recomendam os teus produtos.' },
        { h: 'Marketplace Sync', p: 'Add-on de sincronização do catálogo com marketplaces: stocks e preços alinhados automaticamente em todos os canais.' },
      ],
    },
    steps: {
      eyebrow: 'Como funciona',
      h2: 'Do feed à venda, em três passos',
      items: [
        { h: 'Auditoria gratuita do feed', p: 'Analisamos o teu catálogo e dizemos-te concretamente o que falta: GTIN, atributos, erros de Merchant Center, oportunidades de correspondência no comparador.' },
        { h: 'Ligação e ativação', p: 'Ligamos a tua loja ao nosso CSS e ao comparador. A ativação demora 24–48 horas, sem modificações no teu site.' },
        { h: 'Monitorização diária', p: 'Acompanhamos preços, disponibilidade e desempenho. Recebes relatórios claros: o que se vendeu, o que custa o clique, onde podes crescer.' },
      ],
    },
    pricing: {
      eyebrow: 'Preços transparentes',
      h2: 'Grelha oficial CatyAI',
      sub: 'Setup único + subscrição mensal + comissão sobre o orçamento de ads. Sem custos ocultos, sem períodos de teste — com resultados mensuráveis.',
      badge: 'TARIFA DE LANÇAMENTO',
      setupSuffix: ' setup',
      monthlySuffix: '/mês',
      commission: 'Comissão',
      adBudget: ' do orçamento de ads',
      plans: [
        { name: 'Entry', launch: true, sku: 'até 1.000 SKU', setup: '500€', monthly: '200€', commission: '5%', features: ['Listagem no comparador', 'Relatório mensal'] },
        { name: 'Starter', launch: true, sku: '1.001–3.000 SKU', setup: '700€', monthly: '250€', commission: '5%', features: ['CSS + comparador', 'Feed management'] },
        { name: 'Growth', sku: '3.001–10.000 SKU', setup: '3.000€', monthly: '600€', commission: '5%', features: ['Tudo do Starter', 'Otimização semântica GTIN'] },
        { name: 'Pro', sku: '10.001–50.000 SKU', setup: '6.000€', monthly: '1.200€', commission: '4%', features: ['Visibilidade em IA incluída', 'Manager dedicado'] },
        { name: 'Enterprise', sku: 'mais de 50.000 SKU', setup: 'custom', monthly: '', commission: '3–4%', features: ['Arquitetura multi-conta GMC', 'SLA e integração API'] },
      ],
      addons: [
        { h: 'Marketplace Sync', p: '200€ setup/canal + 150€/mês (standalone: 300€ setup + 200€/mês). Sincronização de stocks e preços com marketplaces.' },
        { h: 'Canais adicionais', p: '+50€/mês por cada canal extra nos pacotes Entry e Starter.' },
      ],
      note: 'A tarifa de lançamento é válida para os primeiros 10 clientes, até 31.12.2026. Condições: setup pago ao assinar, período mínimo de 6 meses para Entry e Starter. Os preços apresentados não incluem IVA.',
    },
    faq: {
      h2: 'Perguntas frequentes',
      items: [
        { q: 'O que é CSS e por que o clique é mais barato?', a: 'CSS (Comparison Shopping Services) é o programa do Google através do qual serviços independentes de comparação de preços — como nós — podem listar produtos no Google Shopping. O leilão através de um CSS tem uma vantagem de custo integrada no mecanismo do Google, o que se traduz em até ~20% de poupança por clique em relação à conta padrão. A visibilidade dos produtos mantém-se idêntica.' },
        { q: 'Tenho de mudar algo na minha loja online?', a: 'Não. Trabalhamos com base no feed de produtos que já tens (ou construímo-lo nós). Não instalamos scripts no teu site e não tocamos na tua plataforma — seja GoMag, Shopify, WooCommerce ou outra.' },
        { q: 'Quanto tempo até os meus produtos aparecerem?', a: 'A ativação CSS e a listagem no comparador demoram 24–48 horas a partir da receção do feed válido. A primeira otimização do feed (se necessária) acrescenta, em regra, mais 1–2 dias.' },
        { q: 'O que significa «visibilidade em IA» concretamente?', a: 'Os assistentes de IA (ChatGPT, Gemini, Perplexity) recomendam produtos com base nos dados que conseguem ler e perceber. Garantimos que o teu catálogo tem dados estruturados corretos, preços reais e páginas indexáveis — as condições para uma IA poder citar-te. Monitorizamos a tua presença nas respostas da IA e reportamos.' },
        { q: 'Posso cancelar a qualquer momento?', a: 'O período mínimo é de 6 meses para os pacotes Entry e Starter (o tempo real em que um canal deste tipo atinge desempenho). Depois, a colaboração continua mês a mês, sem obrigações.' },
      ],
    },
    finalCta: {
      h2: 'Pede a auditoria gratuita do teu feed',
      p: 'Dizemos-te em 48 horas o que estás a perder agora: cliques pagos demasiado caros, produtos invisíveis, GTIN em falta.',
      cta: 'contact@catyai.io',
    },
  },

  fr: {
    meta: {
      title: 'Campagnes Google Shopping & Comparateur de Prix — CatyAI',
      desc: 'CatyAI : campagnes Google Shopping via CSS avec jusqu\'à ~20% d\'économie par clic, comparateur de prix avec moteur sémantique EAN/GTIN et visibilité dans les recherches IA.',
    },
    hero: {
      eyebrow: 'CSS · Comparateur de prix · Visibilité IA',
      titlePre: 'Vos produits, ',
      titleAccent: 'en première place',
      titlePost: ' sur Google Shopping. Au bon coût.',
      sub: 'Nous sommes opérateur CSS agréé Google et nous construisons le comparateur de prix avec un moteur sémantique propriétaire. Nous connectons votre catalogue, nettoyons votre feed et amenons vos produits exactement là où les acheteurs cherchent.',
      cta1: 'Demander une consultation gratuite',
      cta2: 'Voir les prix',
    },
    stats: [
      { v: '2,8 M+', l: 'produits dans notre comparateur' },
      { v: '3,7 M', l: 'vecteurs dans le moteur sémantique' },
      { v: '500 000+', l: 'produits traités quotidiennement à partir des feeds' },
      { v: '24–48h', l: 'activation CSS pour votre boutique' },
    ],
    css: {
      eyebrow: 'Google Shopping via CSS',
      h2: 'Le même clic, jusqu\'à ~20% moins cher',
      p: 'En tant que partenaire CSS (Comparison Shopping Services), nous listons vos produits dans Google Shopping via notre infrastructure — pas via le compte Google standard. Le mécanisme du programme CSS réduit le coût réel du clic, et la différence reste chez vous.',
      bullets: [
        'Vos produits apparaissent dans Shopping sans le surcoût de l\'enchère standard',
        'Vous gardez le contrôle total : vous choisissez quels produits et quel budget promouvoir',
        'Migration depuis votre compte Merchant Center sans perte d\'historique de performance',
        'Reporting transparent — vous voyez exactement ce que vous payez et ce que vous recevez',
      ],
      badge: 'Jusqu\'à ~20% d\'économie par clic, grâce au mécanisme officiel CSS',
    },
    comparator: {
      eyebrow: 'Comparateur de prix avec moteur sémantique',
      h2: 'Le même produit, tous les prix. Sans doublons.',
      p: 'Notre comparateur n\'apparie pas les produits par titre. Notre moteur sémantique propriétaire comprend ce qu\'est le produit et le lie sur la base des codes EAN/GTIN — ainsi le même produit de 5 boutiques apparaît une seule fois, avec les 5 prix côte à côte.',
      bullets: [
        'Plus de 2,8 millions de produits indexés et mis à jour quotidiennement',
        'Appariement EAN/GTIN + appariement sémantique pour les produits sans code',
        'Offres similaires générées par le moteur de vecteurs, pas par des règles manuelles',
        'Le trafic du comparateur arrive directement sur votre page produit',
      ],
    },
    ai: {
      eyebrow: 'Visibilité dans les recherches IA',
      h2: 'Quand le client interroge l\'IA, la réponse doit être votre produit',
      p: 'De plus en plus d\'acheteurs ne cherchent plus sur Google — ils interrogent ChatGPT, Gemini ou Perplexity. Nous optimisons la structure de votre catalogue (données structurées, feeds propres, contenu lisible par les machines) pour que les assistants IA vous trouvent et vous recommandent.',
      bullets: [
        'Données structurées et feeds préparés pour la consommation par les agents IA',
        'Pages produit indexables, rapides, avec prix et disponibilité corrects',
        'Nous surveillons votre apparition dans les réponses de l\'IA et ajustons en continu',
      ],
    },
    services: {
      eyebrow: 'Ce que nous faisons concrètement',
      h2: 'L\'infrastructure complète de votre catalogue',
      sub: 'Nous ne vendons pas de promesses. Nous opérons des feeds, des comptes Merchant Center et des pipelines de données quotidiennement — exactement ce que vous voyez ci-dessous.',
      items: [
        { h: 'Feed management', p: 'Nous nettoyons, complétons et validons votre feed produits : titres, attributs, GTIN, catégories Google. Le feed est la fondation — tout le reste en dépend.' },
        { h: 'Google Merchant Center', p: 'Nous configurons et gérons les comptes Merchant Center, y compris les architectures multi-comptes. Nous résolvons suspensions, avertissements et erreurs de feed.' },
        { h: 'Comparateur de prix', p: 'Nous listons vos produits dans notre comparateur, avec des prix mis à jour quotidiennement et du trafic envoyé directement vers vos pages produit.' },
        { h: 'Campagnes CSS', p: 'Nous déplaçons vos campagnes Shopping vers notre CSS, avec une économie allant jusqu\'à ~20% par clic et la même visibilité dans Google.' },
        { h: 'Visibilité IA (GEO)', p: 'Nous préparons votre catalogue pour l\'ère de la recherche conversationnelle : les assistants IA lisent, comprennent et recommandent vos produits.' },
        { h: 'Marketplace Sync', p: 'Add-on de synchronisation du catalogue avec les marketplaces : stocks et prix alignés automatiquement sur tous les canaux.' },
      ],
    },
    steps: {
      eyebrow: 'Comment ça marche',
      h2: 'Du feed à la vente, en trois étapes',
      items: [
        { h: 'Audit gratuit du feed', p: 'Nous analysons votre catalogue et vous disons concrètement ce qui manque : GTIN, attributs, erreurs Merchant Center, opportunités d\'appariement dans le comparateur.' },
        { h: 'Connexion et activation', p: 'Nous connectons votre boutique à notre CSS et au comparateur. L\'activation dure 24–48 heures, sans modification de votre site.' },
        { h: 'Surveillance quotidienne', p: 'Nous suivons les prix, la disponibilité et la performance. Vous recevez des rapports clairs : ce qui s\'est vendu, ce que coûte le clic, où vous pouvez croître.' },
      ],
    },
    pricing: {
      eyebrow: 'Tarifs transparents',
      h2: 'Grille tarifaire officielle CatyAI',
      sub: 'Setup unique + abonnement mensuel + commission sur le budget publicitaire. Sans coûts cachés, sans périodes d\'essai — avec des résultats mesurables.',
      badge: 'TARIF DE LANCEMENT',
      setupSuffix: ' setup',
      monthlySuffix: '/mois',
      commission: 'Commission',
      adBudget: ' du budget publicitaire',
      plans: [
        { name: 'Entry', launch: true, sku: 'jusqu\'à 1 000 SKU', setup: '500€', monthly: '200€', commission: '5%', features: ['Listage dans le comparateur', 'Rapport mensuel'] },
        { name: 'Starter', launch: true, sku: '1 001–3 000 SKU', setup: '700€', monthly: '250€', commission: '5%', features: ['CSS + comparateur', 'Feed management'] },
        { name: 'Growth', sku: '3 001–10 000 SKU', setup: '3 000€', monthly: '600€', commission: '5%', features: ['Tout ce qui est dans Starter', 'Optimisation sémantique GTIN'] },
        { name: 'Pro', sku: '10 001–50 000 SKU', setup: '6 000€', monthly: '1 200€', commission: '4%', features: ['Visibilité IA incluse', 'Manager dédié'] },
        { name: 'Enterprise', sku: 'plus de 50 000 SKU', setup: 'custom', monthly: '', commission: '3–4%', features: ['Architecture multi-comptes GMC', 'SLA et intégration API'] },
      ],
      addons: [
        { h: 'Marketplace Sync', p: '200€ setup/canal + 150€/mois (standalone : 300€ setup + 200€/mois). Synchronisation des stocks et prix avec les marketplaces.' },
        { h: 'Canaux supplémentaires', p: '+50€/mois pour chaque canal supplémentaire sur les offres Entry et Starter.' },
      ],
      note: 'Le tarif de lancement est valable pour les 10 premiers clients, jusqu\'au 31.12.2026. Conditions : setup payé à la signature, période minimale de 6 mois pour Entry et Starter. Les tarifs affichés n\'incluent pas la TVA.',
    },
    faq: {
      h2: 'Questions fréquentes',
      items: [
        { q: 'Qu\'est-ce que le CSS et pourquoi le clic est-il moins cher ?', a: 'Le CSS (Comparison Shopping Services) est le programme Google via lequel des services indépendants de comparaison de prix — comme nous — peuvent lister des produits dans Google Shopping. L\'enchère via un CSS dispose d\'un avantage de coût intégré dans le mécanisme de Google, ce qui se traduit par jusqu\'à ~20% d\'économie par clic par rapport au compte standard. La visibilité des produits reste identique.' },
        { q: 'Dois-je modifier quelque chose dans ma boutique en ligne ?', a: 'Non. Nous travaillons sur la base du feed produits que vous avez déjà (ou nous le construisons). Nous n\'installons pas de scripts sur votre site et nous ne touchons pas votre plateforme — que ce soit GoMag, Shopify, WooCommerce ou autre chose.' },
        { q: 'Combien de temps avant que mes produits apparaissent ?', a: 'L\'activation CSS et le listage dans le comparateur prennent 24–48 heures à partir de la réception du feed valide. La première optimisation du feed (si nécessaire) ajoute en général encore 1–2 jours.' },
        { q: 'Que signifie « visibilité IA » concrètement ?', a: 'Les assistants IA (ChatGPT, Gemini, Perplexity) recommandent des produits sur la base des données qu\'ils peuvent lire et comprendre. Nous nous assurons que votre catalogue dispose de données structurées correctes, de prix réels et de pages indexables — les conditions pour qu\'une IA puisse vous citer. Nous surveillons votre présence dans les réponses de l\'IA et nous faisons rapport.' },
        { q: 'Puis-je arrêter à tout moment ?', a: 'La période minimale est de 6 mois pour les offres Entry et Starter (le temps réel pendant lequel un canal de ce type atteint ses performances). Ensuite, la collaboration continue au mois, sans obligations.' },
      ],
    },
    finalCta: {
      h2: 'Demandez l\'audit gratuit de votre feed',
      p: 'Nous vous disons en 48 heures ce que vous perdez actuellement : des clics payés trop cher, des produits invisibles, des GTIN manquants.',
      cta: 'contact@catyai.io',
    },
  },
}

function Eyebrow({ children }) {
  return (
    <p className="text-sm font-semibold uppercase tracking-widest text-gold mb-4">{children}</p>
  )
}

export default function Campanii({ locale }) {
  const [openFaq, setOpenFaq] = useState(0)
  const [scrolled, setScrolled] = useState(false)
  const [lang, setLang] = useState(locale || 'en')

  useEffect(() => {
    if (locale) return
    const saved = localStorage.getItem('catyai_lang')
    if (saved && T[saved]) setLang(saved)
  }, [locale])

  useEffect(() => { if (!locale) localStorage.setItem('catyai_lang', lang) }, [lang, locale])

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 10)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  const t = T[lang] || T.en

  return (
    <>
      <SEO
        title={t.meta.title}
        description={t.meta.desc}
        image="https://catyai.io/assets/campanii/hero.png"
        url={pageUrl(SLUG, locale || lang)}
        lang={lang}
        alternates={alternatesFor(SLUG)}
      />
      <Helmet>
        <html lang={lang} />
      </Helmet>

      <div className="min-h-screen bg-[#0a0f1c] text-[#c7d0e0] font-sans antialiased">
        <GlobalHeader lang={lang} setLang={setLang} scrolled={scrolled} />

        <main>
      {/* Secțiunea 1 — Hero */}
      <section className="relative overflow-hidden" style={{ backgroundColor: '#0A1628' }}>
        <div className="max-w-7xl mx-auto px-6 pt-32 pb-20 lg:pt-40 lg:pb-28 grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <Eyebrow>{t.hero.eyebrow}</Eyebrow>
            <h1 className="text-4xl lg:text-5xl font-bold leading-tight mb-6" style={{ color: '#E9EDF4' }}>
              {t.hero.titlePre}<span className="text-gold">{t.hero.titleAccent}</span>{t.hero.titlePost}
            </h1>
            <p className="text-lg mb-8" style={{ color: '#E9EDF4', opacity: 0.85 }}>
              {t.hero.sub}
            </p>
            <div className="flex flex-wrap gap-4">
              <a
                href="mailto:contact@catyai.io"
                className="inline-block bg-gold hover:bg-[#D4B57A] text-[#0A1628] font-semibold px-8 py-4 rounded-lg transition-colors"
              >
                {t.hero.cta1}
              </a>
              <a
                href="#preturi"
                className="inline-block border border-[#C8A165] text-gold hover:bg-[#C8A165] hover:text-[#0A1628] font-semibold px-8 py-4 rounded-lg transition-colors"
              >
                {t.hero.cta2}
              </a>
            </div>
          </div>
          <div className="relative">
            <img
              src="/assets/campanii/hero.png"
              alt={t.meta.title}
              className="w-full h-auto rounded-2xl"
              style={{ maskImage: 'linear-gradient(to right, black 70%, transparent 100%)', WebkitMaskImage: 'linear-gradient(to right, black 70%, transparent 100%)' }}
              width="880"
              height="660"
            />
          </div>
        </div>
      </section>

      {/* Secțiunea 2 — Bară cifre */}
      <section style={{ backgroundColor: '#0F1F38' }}>
        <div className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">
          {t.stats.map((s) => (
            <div key={s.l}>
              <p className="text-3xl lg:text-4xl font-bold text-gold mb-2">{s.v}</p>
              <p className="text-sm" style={{ color: '#E9EDF4', opacity: 0.75 }}>{s.l}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Secțiunea 3 — CSS */}
      <section id="css" className="scroll-mt-24" style={{ backgroundColor: '#0A1628' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <Eyebrow>{t.css.eyebrow}</Eyebrow>
            <h2 className="text-3xl lg:text-4xl font-bold mb-6" style={{ color: '#E9EDF4' }}>
              {t.css.h2}
            </h2>
            <p className="mb-8" style={{ color: '#E9EDF4', opacity: 0.85 }}>
              {t.css.p}
            </p>
            <ul className="space-y-3 mb-8">
              {t.css.bullets.map((b) => (
                <li key={b} className="flex items-start gap-3" style={{ color: '#E9EDF4', opacity: 0.9 }}>
                  <span className="text-gold mt-1">✓</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
            <p className="inline-block border border-[#C8A165] rounded-full px-5 py-2 text-sm font-semibold text-gold">
              {t.css.badge}
            </p>
          </div>
          <div>
            <img
              src="/assets/campanii/css-shopping.png"
              alt={t.css.h2}
              className="w-full h-auto rounded-2xl"
              width="880"
              height="660"
            />
          </div>
        </div>
      </section>

      {/* Secțiunea 4 — Comparator */}
      <section id="comparator" className="scroll-mt-24" style={{ backgroundColor: '#0F1F38' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center">
          <div className="order-last lg:order-first">
            <img
              src="/assets/campanii/motor-semantic.png"
              alt={t.comparator.h2}
              className="w-full h-auto rounded-2xl"
              width="880"
              height="660"
            />
          </div>
          <div>
            <Eyebrow>{t.comparator.eyebrow}</Eyebrow>
            <h2 className="text-3xl lg:text-4xl font-bold mb-6" style={{ color: '#E9EDF4' }}>
              {t.comparator.h2}
            </h2>
            <p className="mb-8" style={{ color: '#E9EDF4', opacity: 0.85 }}>
              {t.comparator.p}
            </p>
            <ul className="space-y-3">
              {t.comparator.bullets.map((b) => (
                <li key={b} className="flex items-start gap-3" style={{ color: '#E9EDF4', opacity: 0.9 }}>
                  <span className="text-gold mt-1">✓</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>

      {/* Secțiunea 5 — Vizibilitate AI */}
      <section id="ai" className="scroll-mt-24" style={{ backgroundColor: '#0A1628' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28 grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <Eyebrow>{t.ai.eyebrow}</Eyebrow>
            <h2 className="text-3xl lg:text-4xl font-bold mb-6" style={{ color: '#E9EDF4' }}>
              {t.ai.h2}
            </h2>
            <p className="mb-8" style={{ color: '#E9EDF4', opacity: 0.85 }}>
              {t.ai.p}
            </p>
            <ul className="space-y-3">
              {t.ai.bullets.map((b) => (
                <li key={b} className="flex items-start gap-3" style={{ color: '#E9EDF4', opacity: 0.9 }}>
                  <span className="text-gold mt-1">✓</span>
                  <span>{b}</span>
                </li>
              ))}
            </ul>
          </div>
          <div>
            <img
              src="/assets/campanii/vizibilitate-ai.png"
              alt={t.ai.h2}
              className="w-full h-auto rounded-2xl"
              width="880"
              height="660"
            />
          </div>
        </div>
      </section>

      {/* Secțiunea 6 — Carduri servicii */}
      <section style={{ backgroundColor: '#0F1F38' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28">
          <div className="text-center max-w-3xl mx-auto mb-14">
            <Eyebrow>{t.services.eyebrow}</Eyebrow>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4" style={{ color: '#E9EDF4' }}>
              {t.services.h2}
            </h2>
            <p style={{ color: '#E9EDF4', opacity: 0.8 }}>
              {t.services.sub}
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {t.services.items.map((s) => (
              <div key={s.h} className="rounded-2xl p-8 border border-[#1E3355]" style={{ backgroundColor: '#0A1628' }}>
                <h3 className="text-xl font-bold mb-3 text-gold">{s.h}</h3>
                <p className="text-sm leading-relaxed" style={{ color: '#E9EDF4', opacity: 0.85 }}>{s.p}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Secțiunea 7 — 3 pași */}
      <section style={{ backgroundColor: '#0A1628' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28">
          <div className="text-center max-w-3xl mx-auto mb-14">
            <Eyebrow>{t.steps.eyebrow}</Eyebrow>
            <h2 className="text-3xl lg:text-4xl font-bold" style={{ color: '#E9EDF4' }}>
              {t.steps.h2}
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {t.steps.items.map((s, i) => (
              <div key={s.h} className="rounded-2xl p-8" style={{ backgroundColor: '#0F1F38' }}>
                <p className="text-4xl font-bold text-gold mb-4">{String(i + 1).padStart(2, '0')}</p>
                <h3 className="text-xl font-bold mb-3" style={{ color: '#E9EDF4' }}>{s.h}</h3>
                <p className="text-sm leading-relaxed" style={{ color: '#E9EDF4', opacity: 0.85 }}>{s.p}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Secțiunea 8 — Prețuri */}
      <section id="preturi" className="scroll-mt-24" style={{ backgroundColor: '#F7F4EE' }}>
        <div className="max-w-7xl mx-auto px-6 py-20 lg:py-28">
          <div className="text-center max-w-3xl mx-auto mb-14">
            <p className="text-sm font-semibold uppercase tracking-widest text-[#A88A52] mb-4">{t.pricing.eyebrow}</p>
            <h2 className="text-3xl lg:text-4xl font-bold mb-4 text-[#0A1628]">{t.pricing.h2}</h2>
            <p className="text-[#0A1628]" style={{ opacity: 0.75 }}>
              {t.pricing.sub}
            </p>
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-5 gap-6 mb-10">
            {t.pricing.plans.map((p) => (
              <div key={p.name} className="rounded-2xl p-6 bg-white shadow-sm border border-[#E5DFD3] flex flex-col">
                {p.badge || t.pricing.badge ? (
                  <span className="self-start text-xs font-bold uppercase tracking-wide bg-gold text-[#0A1628] rounded-full px-3 py-1 mb-3">
                    {t.pricing.badge}
                  </span>
                ) : null}
                <h3 className="text-xl font-bold text-[#0A1628] mb-1">{p.name}</h3>
                <p className="text-sm text-[#0A1628] mb-4" style={{ opacity: 0.6 }}>{p.sku}</p>
                <p className="text-2xl font-bold text-[#0A1628]">{p.setup}{t.pricing.setupSuffix}</p>
                {p.monthly && <p className="text-lg font-semibold text-[#0A1628] mb-3">{p.monthly}{t.pricing.monthlySuffix}</p>}
                {!p.monthly && <p className="text-lg font-semibold text-[#0A1628] mb-3" style={{ opacity: 0.6 }}>—</p>}
                <p className="text-sm font-medium text-[#A88A52] mb-4">{t.pricing.commission} {p.commission}{t.pricing.adBudget}</p>
                <ul className="space-y-2 text-sm text-[#0A1628] mt-auto">
                  {p.features.map((f) => (
                    <li key={f} className="flex items-start gap-2">
                      <span className="text-[#A88A52] mt-0.5">✓</span>
                      <span>{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            <div className="rounded-2xl p-6 bg-white shadow-sm border border-[#E5DFD3]">
              <h3 className="text-lg font-bold text-[#0A1628] mb-2">{t.pricing.addons[0].h}</h3>
              <p className="text-sm text-[#0A1628]" style={{ opacity: 0.75 }}>
                {t.pricing.addons[0].p}
              </p>
            </div>
            <div className="rounded-2xl p-6 bg-white shadow-sm border border-[#E5DFD3]">
              <h3 className="text-lg font-bold text-[#0A1628] mb-2">{t.pricing.addons[1].h}</h3>
              <p className="text-sm text-[#0A1628]" style={{ opacity: 0.75 }}>
                {t.pricing.addons[1].p}
              </p>
            </div>
          </div>
          <p className="text-xs text-[#0A1628] text-center" style={{ opacity: 0.6 }}>
            {t.pricing.note}
          </p>
        </div>
      </section>

      {/* Secțiunea 9 — FAQ */}
      <section style={{ backgroundColor: '#0F1F38' }}>
        <div className="max-w-4xl mx-auto px-6 py-20 lg:py-28">
          <div className="text-center mb-14">
            <h2 className="text-3xl lg:text-4xl font-bold" style={{ color: '#E9EDF4' }}>
              {t.faq.h2}
            </h2>
          </div>
          <div className="space-y-4">
            {t.faq.items.map((f, i) => {
              const open = openFaq === i
              return (
                <div key={f.q} className="rounded-2xl border border-[#1E3355]" style={{ backgroundColor: '#0A1628' }}>
                  <button
                    type="button"
                    onClick={() => setOpenFaq(open ? -1 : i)}
                    className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left"
                    aria-expanded={open}
                  >
                    <span className="font-semibold" style={{ color: '#E9EDF4' }}>{f.q}</span>
                    <span className="text-gold text-xl leading-none">{open ? '−' : '+'}</span>
                  </button>
                  {open && (
                    <p className="px-6 pb-6 text-sm leading-relaxed" style={{ color: '#E9EDF4', opacity: 0.8 }}>
                      {f.a}
                    </p>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* Secțiunea 10 — CTA final */}
      <section style={{ backgroundColor: '#0A1628' }}>
        <div className="max-w-4xl mx-auto px-6 py-20 lg:py-24 text-center">
          <h2 className="text-3xl lg:text-4xl font-bold mb-4" style={{ color: '#E9EDF4' }}>
            {t.finalCta.h2}
          </h2>
          <p className="mb-8" style={{ color: '#E9EDF4', opacity: 0.85 }}>
            {t.finalCta.p}
          </p>
          <a
            href="mailto:contact@catyai.io"
            className="inline-block bg-gold hover:bg-[#D4B57A] text-[#0A1628] font-semibold px-8 py-4 rounded-lg transition-colors"
          >
            {t.finalCta.cta}
          </a>
        </div>
      </section>
        </main>

        <FooterV9 lang={lang} />
      </div>
    </>
  )
}
